In [1]:
import pandas as pd
import numpy as np
import zipfile
from datetime import date, timedelta

In [2]:
date = date.today() - timedelta(5)
exchanges = ['HSX', 'HNX']
list_ = []
with zipfile.ZipFile('C:\\Users\\Win 10\\Desktop\\SSI_DauTruong\\history.zip') as myzip:
    for exchange in exchanges:
        with myzip.open('CafeF.'+exchange+'.Upto'+date.strftime('%d.%m.%Y')+'.csv') as myfile:
            data = pd.read_csv(myfile, header = 0,names = ['Ticker','Date','Open','High','Low','Close','Volume'])
            list_.append(data)
frame = pd.concat(list_)
frame['Date'] = pd.to_datetime(frame.Date, format='%Y%m%d')

In [3]:
frame.head()

     Ticker       Date   Open   High    Low  Close   Volume
0  FUCVREIT 2019-11-29   7.91   7.91   7.91   7.91      210
1       VPI 2019-11-29  41.30  42.00  40.80  42.00   526510
2       VPK 2019-11-29   2.05   2.05   2.00   2.00    88400
3       VPS 2019-11-29  10.70  10.70  10.70  10.70     1000
4       VRC 2019-11-29  22.30  23.00  21.10  23.00  1353600

In [4]:
print(type(date))

<class 'datetime.date'>

In [5]:
min(frame['Date'])

Timestamp('2000-07-28 00:00:00')

In [6]:
dates = frame['Date'].unique()

In [7]:
dates = pd.to_datetime(dates, format='%Y%m%d')

In [8]:
date

datetime.date(2019, 11, 29)

In [9]:
dates = dates.sort_values()

In [10]:
dates

DatetimeIndex(['2000-07-28', '2000-07-31', '2000-08-02', '2000-08-04',
               '2000-08-07', '2000-08-09', '2000-08-11', '2000-08-14',
               '2000-08-16', '2000-08-18',
               ...
               '2019-11-18', '2019-11-19', '2019-11-20', '2019-11-21',
               '2019-11-22', '2019-11-25', '2019-11-26', '2019-11-27',
               '2019-11-28', '2019-11-29'],
              dtype='datetime64[ns]', length=4679, freq=None)

In [11]:
stocks = list(frame['Ticker'].unique())

In [12]:
dictdf = {}
not_unique = 0
not_unique = 0
for each in stocks:
    if len(each) < 4:
        thisframe = frame[frame['Ticker'] == each]
        thisframe.index = thisframe.Date
        thisframe.drop_duplicates(inplace=True)
        dictdf[each] = thisframe

C:\Users\Win 10\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [21]:
ACB = dictdf['VTV'].sort_index()

In [22]:
missingdate = dates.difference(ACB.index)

In [23]:
dfblank = pd.DataFrame(index=missingdate)

In [24]:
dfful = pd.concat([dfblank,ACB],join='outer')
dfful = dfful.sort_index()
dfful

C:\Users\Win 10\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

            Close       Date  High  Low  Open Ticker  Volume
2000-07-28    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2000-07-31    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2000-08-02    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2000-08-04    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2000-08-07    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2000-08-09    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2000-08-11    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2000-08-14    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2000-08-16    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2000-08-18    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2000-08-21    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2000-08-23    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2000-08-25    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2000-08-28    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2000-08-30    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2000-09-01    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2000-09-06    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2000-09-08    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2000-09-11    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2000-09-13    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2000-09-15    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2000-09-18    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2000-09-20    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2000-09-22    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2000-09-25    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2000-09-27    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2000-09-29    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2000-10-02    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2000-10-04    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2000-10-06    NaN        NaT   NaN  NaN   NaN    NaN     NaN
...           ...        ...   ...  ...   ...    ...     ...
2019-10-21    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2019-10-22    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2019-10-23    8.7 2019-10-23   8.7  8.7   8.7    VTV    29.0
2019-10-24    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2019-10-25    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2019-10-28    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2019-10-29    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2019-10-30    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2019-10-31    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2019-11-01    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2019-11-04    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2019-11-05    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2019-11-06    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2019-11-07    9.5 2019-11-07   9.5  9.5   9.5    VTV   100.0
2019-11-08    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2019-11-11    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2019-11-12    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2019-11-13    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2019-11-14    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2019-11-15    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2019-11-18    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2019-11-19    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2019-11-20    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2019-11-21    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2019-11-22    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2019-11-25    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2019-11-26    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2019-11-27    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2019-11-28    NaN        NaT   NaN  NaN   NaN    NaN     NaN
2019-11-29    NaN        NaT   NaN  NaN   NaN    NaN     NaN

[4679 rows x 7 columns]

In [19]:
dfful.drop(['Date'],axis=1,inplace=True)

In [20]:
dfful

            Close  High   Low  Open Ticker     Volume
2000-07-28    NaN   NaN   NaN   NaN    NaN        NaN
2000-07-31    NaN   NaN   NaN   NaN    NaN        NaN
2000-08-02    NaN   NaN   NaN   NaN    NaN        NaN
2000-08-04    NaN   NaN   NaN   NaN    NaN        NaN
2000-08-07    NaN   NaN   NaN   NaN    NaN        NaN
2000-08-09    NaN   NaN   NaN   NaN    NaN        NaN
2000-08-11    NaN   NaN   NaN   NaN    NaN        NaN
2000-08-14    NaN   NaN   NaN   NaN    NaN        NaN
2000-08-16    NaN   NaN   NaN   NaN    NaN        NaN
2000-08-18    NaN   NaN   NaN   NaN    NaN        NaN
2000-08-21    NaN   NaN   NaN   NaN    NaN        NaN
2000-08-23    NaN   NaN   NaN   NaN    NaN        NaN
2000-08-25    NaN   NaN   NaN   NaN    NaN        NaN
2000-08-28    NaN   NaN   NaN   NaN    NaN        NaN
2000-08-30    NaN   NaN   NaN   NaN    NaN        NaN
2000-09-01    NaN   NaN   NaN   NaN    NaN        NaN
2000-09-06    NaN   NaN   NaN   NaN    NaN        NaN
2000-09-08    NaN   NaN   NaN   NaN    NaN        NaN
2000-09-11    NaN   NaN   NaN   NaN    NaN        NaN
2000-09-13    NaN   NaN   NaN   NaN    NaN        NaN
2000-09-15    NaN   NaN   NaN   NaN    NaN        NaN
2000-09-18    NaN   NaN   NaN   NaN    NaN        NaN
2000-09-20    NaN   NaN   NaN   NaN    NaN        NaN
2000-09-22    NaN   NaN   NaN   NaN    NaN        NaN
2000-09-25    NaN   NaN   NaN   NaN    NaN        NaN
2000-09-27    NaN   NaN   NaN   NaN    NaN        NaN
2000-09-29    NaN   NaN   NaN   NaN    NaN        NaN
2000-10-02    NaN   NaN   NaN   NaN    NaN        NaN
2000-10-04    NaN   NaN   NaN   NaN    NaN        NaN
2000-10-06    NaN   NaN   NaN   NaN    NaN        NaN
...           ...   ...   ...   ...    ...        ...
2019-10-21   23.4  24.2  23.4  24.0    ACB  2742188.0
2019-10-22   23.5  23.5  23.3  23.4    ACB  1660272.0
2019-10-23   23.5  23.7  23.5  23.5    ACB   983685.0
2019-10-24   23.6  23.6  23.4  23.6    ACB   921275.0
2019-10-25   23.6  23.6  23.4  23.6    ACB  1105479.0
2019-10-28   23.7  23.9  23.6  23.6    ACB  1090296.0
2019-10-29   23.7  23.9  23.6  23.8    ACB  1702377.0
2019-10-30   24.3  24.4  23.6  23.8    ACB  7431303.0
2019-10-31   24.1  24.4  24.1  24.3    ACB  1293107.0
2019-11-01   24.2  24.3  23.7  23.7    ACB  1907428.0
2019-11-04   24.6  24.7  24.2  24.2    ACB  3939389.0
2019-11-05   24.6  24.9  24.6  24.7    ACB  3578931.0
2019-11-06   24.6  24.8  24.5  24.8    ACB  2507149.0
2019-11-07   24.6  24.7  24.5  24.6    ACB  2102499.0
2019-11-08   24.8  25.1  24.6  24.9    ACB  3921492.0
2019-11-11   24.7  24.9  24.7  24.8    ACB  1719955.0
2019-11-12   24.7  24.7  24.5  24.7    ACB  1574994.0
2019-11-13   25.0  25.3  24.7  24.7    ACB  3575361.0
2019-11-14   24.5  25.1  24.5  25.0    ACB  2291325.0
2019-11-15   24.4  24.6  24.4  24.4    ACB  1652242.0
2019-11-18   24.1  24.5  24.0  24.4    ACB  2764302.0
2019-11-19   24.2  24.2  24.0  24.1    ACB  1398481.0
2019-11-20   23.9  24.3  23.9  24.3    ACB  1357644.0
2019-11-21   24.0  24.1  22.0  22.0    ACB  1782516.0
2019-11-22   23.2  24.0  23.1  24.0    ACB  3363603.0
2019-11-25   23.4  23.6  23.2  23.3    ACB  1949233.0
2019-11-26   23.6  23.7  23.5  23.5    ACB   577968.0
2019-11-27   23.2  23.7  23.2  23.6    ACB   952900.0
2019-11-28   22.9  23.3  22.8  23.3    ACB  1688171.0
2019-11-29   23.1  23.1  22.8  22.9    ACB   800193.0

[4679 rows x 6 columns]